#!/usr/bin/env python3

import argparse
import itertools
import os
import pathlib
import sys

from boututils.run_wrapper import launch

EXAMPLES_DEFAULT = pathlib.Path("../../../examples")
HERMES_3_DEFAULT = pathlib.Path("../../../hermes-3")
JSON_DEFAULT = pathlib.Path("../../../json_database")

NPROCS = {"tokamak-2D": 12, "tokamak-3D": 12}


def requires_vantage(example_dir):
    return "[vantage]" in pathlib.Path(example_dir / "BOUT.inp").read_text()


def run_examples(
    examples_dir: pathlib.Path,
    hermes3_exe: pathlib.Path,
    json_database: pathlib.Path,
    quiet: bool,
    vantage: bool,
):
    # Specify the number of processors needed by each category of test. If
    # not specified, assume 1.

    failed_tests = []

    for category, examples in itertools.groupby(
        sorted(examples_dir.rglob("*.inp")), lambda p: p.parent.parent
    ):
        category_name = str(category.relative_to(examples_dir))
        print(f"\033[1mRunning tests in category '{category_name}'.\033[0m")
        print(f"Working directory: {category}")
        os.chdir(category)
        for example in examples:
            example_dir = example.parent
            # skip example if Vantage required but Vantage tests not requested
            req_vantage = requires_vantage(example_dir)
            if req_vantage and not vantage:
                continue
            # skip example if Vantage not required but Vantage requested
            if not req_vantage and vantage:
                continue
            # if we need to run this example, create a symlink to the "json_database"
            # this logic works only because [vantage] is only used in all examples of a single category
            # multiple calls to this line result in symlink linking/unlinking errors if
            # two scripts run different examples from the same category synchronously
            # this would occur if
            # $ ./runtest --vantage
            # and
            # $ ./runtest
            # were executed synchronously by
            # $ ctest -j N with N > 1
            # the solution should be to have a different path to the `json_database` for each example
            json_link = category / "json_database"
            json_link.symlink_to(json_database)
            print(f"Running {example_dir.relative_to(examples_dir)}...")
            s, out = launch(
                f"{hermes3_exe} -d {example_dir} nout=1 timestep=1e-3 input:error_on_unused_options=true",
                nproc=NPROCS.get(category_name, 1),
                mthread=1,
                pipe=True,
            )
            if s == 0:
                print("\t\033[92mPASSED!\033[0m")
            else:
                print("\t\033[91mFAILED!\033[0m")
                if not quiet:
                    print(out)
                failed_tests.append(example_dir)
            # unlink the symlink after running the example
            json_link.unlink()
        print()

    print("-" * 80, end="\n\n")
    nfailed = len(failed_tests)
    if nfailed == 0:
        print("\033[92mSUCCESS: All examples were able to start running.\033[0m")
        sys.exit(0)
    else:
        print(f"\033[91mFAILURE: The following {nfailed} examples failed to run")
        print("\t", end="")
        print("\n\t".join(map(str, failed_tests)))
        print("\033[0m")
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--example-dir", default=EXAMPLES_DEFAULT, type=pathlib.Path)
    parser.add_argument("--hermes-exe", default=HERMES_3_DEFAULT, type=pathlib.Path)
    parser.add_argument("--json-database", default=JSON_DEFAULT, type=pathlib.Path)
    parser.add_argument("-q", "--quiet", action="store_true")
    parser.add_argument("--vantage", action="store_true")
    args = parser.parse_args()
    run_examples(
        args.example_dir.resolve(),
        args.hermes_exe.resolve(),
        args.json_database.resolve(),
        args.quiet,
        args.vantage,
    )
